---
apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: dockerhub-secret
type: kubernetes.io/dockercfg
data:
  .dockercfg: ewogICAgImF1dGhzIjogewogICAgICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92Mi8iOiB7CiAgICAgICAgICAgICJhdXRoIjogImJXRnlZMk5oY25KbFkybGpaRHB4ZDJWeWRIa3hNak09IgogICAgICAgIH0KICAgIH0KfQo=
