---
apiVersion: v1
kind: Service
metadata:
  name: weave-flux-memcached
  labels:
    name: weave-flux-memcached
    app: weave-flux
    weave-flux-component: memcached
  namespace: weave
spec:
  clusterIP: None
  ports:
    - name: memcached
      port: 11211
  selector:
    name: weave-flux-memcached
    app: weave-flux
    weave-flux-component: memcached
